Fix Incorrect Attributes and Duplicate Hotkey
This commit fixes the "AttributeError: FlightFollowing object
has no attribute 'lat'" errors upon program start-up.
It also fixes a duplicate hotkey assignment for outside air temperature,
by setting that key to O instead of T.
I also updated the readme file to reflect the added hotkey.
Closes #15, closes #16.